# Fail2ban filter for xrdp. It blocks at a connection phase only
#
# It protects for multiple empty connections, for instance:
# 2026-04-15 12:52:14,916 fail2ban.filter         [14]: INFO    [xrdp-connection-accepted] Found 1.2.3.4 - 2026-04-15 12:52:14
# 2026-04-15 12:52:24,318 fail2ban.filter         [14]: INFO    [xrdp-connection-accepted] Found 1.2.3.4 - 2026-04-15 12:52:24
# 2026-04-15 12:52:42,134 fail2ban.filter         [14]: INFO    [xrdp-connection-accepted] Found 1.2.3.4 - 2026-04-15 12:52:42
#
# From an attacker side it's just multiple telnets:
# telnet 1.2.3.4 3389
# Trying 1.2.3.4...
# Connected to 1.2.3.4.
# Escape character is '^]'.

[Definition]
failregex = ^.*xrdp\[\d+\]: \[INFO \] Socket \d+: connection accepted from \[::ffff:<HOST>\]:\d+

ignoreregex =

# DEV NOTES:
#
# Author: Alexey Tsarev
