# Fail2ban filter for xrdp

[Definition]
failregex = ^.*xrdp\[\d+\]: \[INFO \] Socket \d+: connection accepted from \[::ffff:<HOST>\]:\d+

ignoreregex =

# DEV NOTES:
#
# Author: Alexey Tsarev
#
# Config file "/etc/xrdp/xrdp.ini" has IPv4 setting:
# port=tcp://:3389
