# Fail2ban filter for xrdp

[Definition]
failregex = (?s)^.*xrdp\[\d+\]: \[INFO\s*\] Socket \d+: connection accepted from \[::ffff:<HOST>\]:\d+.*?\n(?:.*\n){0,19}.*xrdp\[\d+\]: \[ERROR\] xrdp_process_main_loop: libxrdp_process_incoming failed.*$

ignoreregex =

# DEV NOTES:
#
# Author: Alexey Tsarev
