music_directory    "/var/lib/mpd/music"
playlist_directory "/var/lib/mpd/playlists"
state_file         "/var/lib/mpd/state"
sticker_file       "/var/lib/mpd/sticker.sql"
db_file            "/var/lib/mpd/tag_cache"

log_file "/dev/stdout"

include_optional "mpd_local.conf"
