version: '3.7'

services:
  sslh:
    build:
      context: ../../images/sslh-head-2020-01-26
      args:
        - http_proxy
        - https_proxy

    image:          alexeytsarev/sslh:head-2020-01-26
    container_name: sslh
    privileged:     true
    network_mode:   host
    restart:        unless-stopped

    environment:
      - TERM=xterm
      - SSLH_OPTS=--transparent -u sslh -p 0.0.0.0:443 --http 127.0.0.1:8443 --ssh 127.0.0.1:22 --openvpn 127.0.0.1:1194
      - SSLH=sslh-select

    labels:
      - SERVICE_NAME=sslh

    logging:
      driver: journald
      options:
        tag: sslh

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro

    ports:
      - 443
