#!/bin/sh

# set -x

ENVS="$(ls -1 .env.*)"

if [ -z "${ENVS}" ]; then
    echo "Fatal: no .env file(s) found"
    exit 1
fi

if [ -n "${VERBOSE}" ] && [ "${VERBOSE}" != "0" ]; then
    v=1
else
    v=0
fi

if [ "${v}" = 1 ]; then
    echo "ENV files:"
    echo "${ENVS}"
    echo
fi

echo "# Autogenerated file! Please use $0" > .env
echo >> .env

# shellcheck disable=SC2086
# shellcheck disable=SC2046
eval env -i $(grep -h -v '^#' ${ENVS}) | sed 's/=\(.*\)/=\1/' >> .env

if [ "${v}" = 1 ]; then
    echo "Done. Print the following '.env' file:"
    cat .env
    echo
fi
