version: '3.7'

services:
  traccar:
    image:          traccar/traccar:debian
    container_name: traccar
    network_mode:   host
    restart:        unless-stopped

    environment:
      - TERM=xterm

    labels:
      - SERVICE_NAME=traccar

    logging:
      driver: journald
      options:
        tag: traccar

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_ROOT}/traccar:/opt/traccar/conf
      - ${DOCKER_ROOT}/log/traccar:/opt/traccar/logs:rw

    ports:
      - 5000-5150:5000-5150
      - 5000-5150:5000-5150/udp
      - 8082:8082
